package views.admin;

import utils.RandomColor;


public class HomeView extends javax.swing.JPanel {

    private boolean isShowLed = false;

    public static void setTimeout(Runnable runnable, int delay) {
        new Thread(() -> {
            try {
                Thread.sleep(delay);
                runnable.run();
            } catch (Exception e) {
                System.err.println(e);
            }
        }).start();
    }

    public HomeView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel = new javax.swing.JLabel();
        jLabel.setText("Quản lý dễ dàng - Thành công mỗi ngày!");
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 28));
        jLabel.setForeground(new java.awt.Color(74, 74, 74));
        jLabel.setBounds(0, 0, 1008, 300);
        add(jLabel);

        setMaximumSize(new java.awt.Dimension(1008, 680));
        setMinimumSize(new java.awt.Dimension(1008, 680));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background.png")));
        jLabel1.setMaximumSize(new java.awt.Dimension(10080000, 68000000));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1008, 680);
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    //GEN-LAST:event_formMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
